export const DISPLAY = 'DISPLAY';
export const TOGGLE_NAVBAR = "TOGGLE_NAVBAR";
export const FOCUS_ON = "FOCUS_ON";
export const SHOW_ANIMATION = "SHOW_ANIMATION"

export const SET_AUTH_TOKEN = 'SET_AUTH_TOKEN';
export const CLEAR_AUTH = 'CLEAR_AUTH';
export const AUTH_REQUEST = 'AUTH_REQUEST';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_ERROR = 'AUTH_ERROR';
export const UPDATED_USER_SUCCESS = "UPDATED_USER_SUCCESS";
export const CHANGE_SUCCESS_MESSAGE = 'CHANGE_SUCCESS_MESSAGE';
export const FETCH_USERS_REQUEST = "FETCH_USERS_REQUEST";
export const FETCH_USERS_SUCCESS = "FETCH_USERS_SUCCESS";
export const FETCH_USERS_ERROR = "FETCH_USERS_ERROR";

export const FETCH_LOCATION_SUCCESS = 'FETCH_LOCATION_SUCCESS';
export const FETCH_LOCATION_ERROR = 'FETCH_LOCATION_ERROR';
export const FETCH_ADDRESS_REQUEST = ' FETCH_ADDRESS_REQUEST';
export const FETCH_ADDRESS_SUCCESS = 'FETCH_ADDRESS_SUCCESS';
export const FETCH_ADDRESS_ERROR = 'FETCH_ADDRESS_ERROR';
export const USER_COORDS_REQUEST = 'USER_COORDS_REQUEST';
export const USER_COORDS_SUCCESS = 'USER_COORDS_SUCCESS';
export const USER_COORDS_ERROR = 'USER_COORDS_ERROR';

export const FETCH_POSTS_REQUEST = "FETCH_POSTS_REQUEST";
export const FETCH_POSTS_SUCCESS = "FETCH_POSTS_SUCCESS";
export const FETCH_POSTS_ERROR = "FETCH_POSTS_ERROR";
export const CREATE_POST_REQUEST = "CREATE_POST_REQUEST";
export const CREATE_POST_SUCCESS = "CREATE_POST_SUCCESS";
export const CREATE_POST_ERROR = "CREATE_POST_ERROR";
export const DELETE_POST_REQUEST = "EDIT_POST_REQUEST";
export const DELETE_POST_SUCCESS = "EDIT_POST_SUCCESS";
export const DELETE_POST_ERROR = "EDIT_POST_ERROR";
export const POST_BEING_EDITED = "POST_BEING_EDITED";
export const ADD_NEW_POST = "ADD_NEW_POST"; 

export const CHANGE_SEARCH_TERM = "CHANGE_SEARCH_TERM";
export const CHANGE_CATEGORY_FILTER = "CHANGE_CATEGORY_FILTER";

export const POST_COMMENT_REQUEST = 'POST_COMMENT_REQUEST'; 
export const POST_COMMENT_SUCCESS = 'POST_COMMENT_SUCCESS'; 
export const POST_COMMENT_ERROR = 'POST_COMMENT_ERROR'; 
export const ADD_NEW_COMMENT = 'ADD_NEW_COMMENT'; 
export const DELETE_COMMENT_REQUEST = 'DELETE_COMMENT_REQUEST';
export const DELETE_COMMENT_SUCCESS = 'DELETE_COMMENT_SUCCESS';
export const DELETE_COMMENT_ERROR = 'DELETE_COMMENT_ERROR';

export const UPDATED_POST = 'UPDATED_POST'
 